// Tenant Ledger module — the ONE home for the move-in-aware tenancy-window
// math: which months a tenant owed rent, what they were expected to pay, what
// they actually paid, and the balances that follow.
//
// Why this module exists: the tenancy-window predicate (a tenant owes rent
// for month m iff they had moved in by the month's end and had not moved out
// before the month's start) used to be hand-copied into ten queries across
// five modules, each annotated with "mirrors the ledger" comments. One rule
// change meant ten edits and a drift hunt. Now the predicate lives here, in
// one fragment builder, and every surface — tenant card, dashboard, arrears,
// reminders, ledger page, statement PDFs, M-Pesa allocation — reads through
// this interface, so the figures cannot disagree.
//
// Interface (deliberately small; everything else is implementation):
//   reportingThroughMonth(year)   — the YTD horizon (live year → current month,
//                                   otherwise December)
//   tenantBalances(tenantId, ...) — per-tenant YTD balances (rent + water +
//                                   derived "previous balance")
//   rentMonths(tenantId, ...)     — per-tenant Jan..throughMonth rent spine
//   occupancyRows(year, ...)      — portfolio truth: which ACTIVE tenants
//                                   occupied which units in which months
//   unitOutstandingRent(...)      — per-unit occupied-months × rent − paid
//
// Implementation notes:
//   * The occupancy predicate is generated by occupiedInMonth() — the only
//     place the date arithmetic exists. Param indices are passed in because
//     each query numbers its own $1..$n.
//   * All money aggregation stays in SQL (NUMERIC-exact); JS derives balances
//     via the shared businessRules helpers and rounds with round2.
//   * The module imports NOTHING from other services — no import cycles; the
//     db pool, businessRules and money utils are the only dependencies.
import { query, queryOne } from '../config/db';
import { balanceDue } from '../utils/businessRules';
import { toNumber, round2 } from '../utils/money';
import { notFound } from '../utils/httpError';

// The reporting year's horizon: the real current month when querying the live
// year, December for past/future years (full-year view). Formerly two private
// copies (financeService.currentMonthForYear, tenantService.currentReportingMonth).
export function reportingThroughMonth(year: number): number {
  const now = new Date();
  return now.getFullYear() === year ? now.getMonth() + 1 : 12;
}

// ---------------------------------------------------------------------------
// The tenancy-window predicate — the ONE copy of the date arithmetic.
// make_date($year, 1, 1) keeps the year parameter integer everywhere (a text
// cast here would clash with billing_year = $n comparisons in the same query).
// The month is an SQL *expression*: spine queries pass their loop variable
// (mm, ms.m), single-month queries pass a parameter ($3). Baking a parameter
// in as the month would test every generated month against the horizon.
// ---------------------------------------------------------------------------
function monthEndExpr(yearIdx: number, monthExpr: string): string {
  return `(make_date($${yearIdx}, 1, 1) + ${monthExpr} * INTERVAL '1 month' - INTERVAL '1 day')`;
}

function monthStartExpr(yearIdx: number, monthExpr: string): string {
  return `(make_date($${yearIdx}, 1, 1) + (${monthExpr} - 1) * INTERVAL '1 month')`;
}

// True for month `monthExpr` iff the tenancy was live for (any part of) that
// month: moved in by the month's end, and not moved out before its start.
function occupiedInMonth(tAlias: string, yearIdx: number, monthExpr: string): string {
  return `(${tAlias}.move_in_date <= ${monthEndExpr(yearIdx, monthExpr)} AND (${tAlias}.move_out_date IS NULL OR ${tAlias}.move_out_date >= ${monthStartExpr(yearIdx, monthExpr)}))`;
}

// ---------------------------------------------------------------------------
// Per-tenant YTD balances — what the tenant card and the reminder composer
// both present. One round trip (the former four-to-five).
// ---------------------------------------------------------------------------
export interface TenantBalances {
  /** The tenant's unit monthly rent (0 when no unit assigned). */
  currentRent: number;
  /** Expected rent for the occupied months of `year` up to `throughMonth`. */
  rentExpectedYtd: number;
  rentPaid: number;
  rentBalance: number;
  /** YTD rent balance minus this month's rent, floored at 0 — the statement's "Previous Balance" line. */
  previousRentBalance: number;
  waterBilled: number;
  waterPaid: number;
  waterBalance: number;
  combinedBalance: number;
}

export async function tenantBalances(
  tenantId: number,
  year: number,
  throughMonth: number = reportingThroughMonth(year)
): Promise<TenantBalances> {
  const row = await queryOne<{
    current_rent: string;
    rent_expected_ytd: string;
    rent_paid: string;
    water_billed: string;
    water_paid: string;
  }>(
    `SELECT COALESCE(u.monthly_rent, 0)::text AS current_rent,
            (COALESCE(u.monthly_rent, 0) * COALESCE(occ.months, 0))::text AS rent_expected_ytd,
            (SELECT COALESCE(SUM(amount), 0) FROM rent_payments WHERE tenant_id = $1 AND billing_year = $2)::text AS rent_paid,
            (SELECT COALESCE(SUM(wmr.water_bill), 0)
             FROM water_meter_readings wmr
             JOIN tenants tw ON tw.unit_id = wmr.unit_id
             WHERE tw.id = $1 AND wmr.billing_year = $2)::text AS water_billed,
            (SELECT COALESCE(SUM(amount), 0) FROM water_payments WHERE tenant_id = $1 AND billing_year = $2)::text AS water_paid
     FROM tenants t
     LEFT JOIN units u ON u.id = t.unit_id
     LEFT JOIN LATERAL (
       SELECT COUNT(*)::int AS months
       FROM generate_series(1, $3::int) AS mm
       WHERE ${occupiedInMonth('t', 2, 'mm')}
     ) occ ON TRUE
     WHERE t.id = $1`,
    [tenantId, year, throughMonth]
  );
  if (!row) throw notFound('Tenant not found.');

  const currentRent = toNumber(row.current_rent);
  const rentExpectedYtd = toNumber(row.rent_expected_ytd);
  const rentPaid = toNumber(row.rent_paid);
  const rentBalance = balanceDue(rentExpectedYtd, rentPaid);
  const waterBilled = toNumber(row.water_billed);
  const waterPaid = toNumber(row.water_paid);
  const waterBalance = balanceDue(waterBilled, waterPaid);
  return {
    currentRent,
    rentExpectedYtd,
    rentPaid,
    rentBalance,
    previousRentBalance: Math.max(round2(rentBalance - Math.min(currentRent, rentBalance)), 0),
    waterBilled,
    waterPaid,
    waterBalance,
    combinedBalance: round2(rentBalance + waterBalance),
  };
}

// ---------------------------------------------------------------------------
// Per-tenant rent spine, Jan..throughMonth. inTenancy marks the months the
// tenancy window covers; expectedRent is the unit rent inside the window and
// 0 outside (byte-compatible with the former ledger/allocation CASE maps).
// ---------------------------------------------------------------------------
export interface LedgerRentMonth {
  month: number;
  inTenancy: boolean;
  expectedRent: number;
  rentPaid: number;
}

export async function rentMonths(
  tenantId: number,
  year: number,
  throughMonth: number = reportingThroughMonth(year)
): Promise<LedgerRentMonth[]> {
  const rows = await query<{ month: number; expected: string | null; paid: string }>(
    `WITH months AS (SELECT generate_series(1, $3::int) AS m),
     tn AS (SELECT unit_id, move_in_date, move_out_date FROM tenants WHERE id = $1),
     rent AS (
       SELECT billing_month AS m, SUM(amount) AS paid
       FROM rent_payments WHERE tenant_id = $1 AND billing_year = $2::int
       GROUP BY billing_month
     )
     SELECT ms.m AS month,
            CASE WHEN tn.unit_id IS NOT NULL
                      AND tn.move_in_date IS NOT NULL
                      AND ${occupiedInMonth('tn', 2, 'ms.m')}
                 THEN u.monthly_rent END AS expected,
            COALESCE(rp.paid, 0) AS paid
     FROM months ms
     CROSS JOIN tn
     LEFT JOIN rent rp ON rp.m = ms.m
     LEFT JOIN units u ON u.id = tn.unit_id
     ORDER BY ms.m`,
    [tenantId, year, throughMonth]
  );
  return rows.map((r) => ({
    month: r.month,
    inTenancy: r.expected !== null,
    expectedRent: r.expected === null ? 0 : toNumber(r.expected),
    rentPaid: toNumber(r.paid),
  }));
}

// ---------------------------------------------------------------------------
// Portfolio occupancy truth — every (month, unit, tenant) the tenancy window
// covers, ACTIVE tenants only. One query feeds the dashboard's YTD and
// current-month expected rent, the monthly rent summary's expected/occupied
// bars, and the per-month tenant status loop.
// ---------------------------------------------------------------------------
export interface OccupancyRow {
  month: number;
  unitId: number;
  unitNumber: string;
  tenantId: number;
  fullName: string;
  monthlyRent: number;
}

export async function occupancyRows(year: number, throughMonth: number = 12): Promise<OccupancyRow[]> {
  const rows = await query<{ month: number; unit_id: number; unit_number: string; tenant_id: number; full_name: string; monthly_rent: string }>(
    `SELECT mb.m AS month, u.id AS unit_id, u.unit_number, t.id AS tenant_id, t.full_name, u.monthly_rent
     FROM generate_series(1, $2::int) AS mb(m)
     JOIN tenants t ON t.status = 'ACTIVE'
     JOIN units u ON u.id = t.unit_id
     WHERE ${occupiedInMonth('t', 1, 'mb.m')}
     ORDER BY mb.m`,
    [year, throughMonth]
  );
  return rows.map((r) => ({
    month: r.month,
    unitId: r.unit_id,
    unitNumber: r.unit_number,
    tenantId: r.tenant_id,
    fullName: r.full_name,
    monthlyRent: toNumber(r.monthly_rent),
  }));
}

// ---------------------------------------------------------------------------
// Per-unit outstanding rent for the dashboard chart: occupied months × the
// unit's rent, minus what the unit was actually paid this year (payments are
// unit-scoped here). Top 10, most outstanding first.
// ---------------------------------------------------------------------------
export async function unitOutstandingRent(year: number, throughMonth: number): Promise<Array<{ unitNumber: string; outstanding: number }>> {
  const rows = await query<{ unit_number: string; outstanding: string }>(
    `SELECT u.unit_number,
            (u.monthly_rent * COALESCE(occ.months, 0)
             - COALESCE((SELECT SUM(rp.amount) FROM rent_payments rp
                         WHERE rp.unit_id = u.id AND rp.billing_year = $1::int), 0))::text AS outstanding
     FROM units u
     JOIN tenants t ON t.unit_id = u.id AND t.status = 'ACTIVE'
     JOIN LATERAL (
       -- Months the tenancy was actually live, matching the ledger semantics —
       -- a unit rented only since September must not show the whole year's
       -- rent as outstanding.
       SELECT COUNT(*)::int AS months
       FROM generate_series(1, $2::int) AS mm
       WHERE ${occupiedInMonth('t', 1, 'mm')}
     ) occ ON TRUE
     ORDER BY outstanding DESC
     LIMIT 10`,
    [year, throughMonth]
  );
  return rows.map((r) => ({ unitNumber: r.unit_number, outstanding: toNumber(r.outstanding) }));
}
